name: simple_chat
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  dio: ^5.5.0+1
  crypto: ^3.0.3
  flutter_secure_storage: ^9.2.2
  flutter_bloc: ^8.1.6
  go_router: ^14.2.3
  flutter:
    sdk: flutter
  connectivity_plus: ^6.0.5
  web_socket_channel: ^3.0.1
  image_picker: ^1.1.2
  bloc_concurrency: ^0.2.5
  stream_transform: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
